# Minimal configuration that will work with GitHub Pages
title: Vincent Kimathi M | Portfolio
email: vkim098@gmail.com
description: "Professional portfolio showcasing my academic background, projects, and technical challenges"
baseurl: ""
url: "https://vincent-kimathi-m.github.io/" # Replace with your GitHub username

# Build settings
theme: jekyll-theme-primer # Use GitHub's default theme temporarily
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
  lab_challenges:
    output: true
