# Minimal configuration that will work with GitHub Pages
title: Vincent Kimathi M | Portfolio
email: vkim098@gmail.com
description: "Professional portfolio showcasing my academic background, projects, and technical challenges"
url: "https://vincent-kimathi-m.github.io/" # Replace with your GitHub username


# Appearance
minimal_mistakes_skin: "dark" # More professional look
search: true

# Build settings
theme: jekyll-theme-minimal # Use GitHub's default theme temporarily
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

  # Navigation
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Collections
collections:
  projects:
    output: true
  lab_challenges:
    output: true
